# Args for FROM directives
ARG NODE_VER=10
ARG RTC_BUILD_TAG=latest

#
# ---- Base Node image ----
FROM node:${NODE_VER} AS base
# The node:8 npm (v 5.6) has some issues, update it to latest
RUN npm install -g npm
# set create and set working directory owned by user
WORKDIR /app
RUN chown node:node /app
USER node

#
# ---- existing rtc build image ----
FROM rifflearning/rtc-build:${RTC_BUILD_TAG} AS build

#
# ---- Release ----
FROM base AS release
LABEL Description="This image runs the riff-rtc server which customizes the chat page w/ config and lti login info"
# This is the production image, set NODE_ENV to reflect that
ENV NODE_ENV=production
# copy production node_modules
COPY --from=build --chown=node:node /app/prod_node_modules ./node_modules/
# copy app project file, build artifacts and configuration files
COPY --from=build --chown=node:node /app/config ./config/
COPY --from=build --chown=node:node /app/server ./server/
COPY --from=build --chown=node:node /app/package.json ./
COPY --from=build --chown=node:node /app/build/index.html ./build/
# allow the port used to be specified, default to 3001
ARG PORT=3001
ENV PORT=$PORT
# expose port
EXPOSE $PORT
# define command to start the riff-rtc server
CMD ["npm", "start"]

